# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

climate: !include climate.yaml
mqtt: !include includes/sensors/sensor_mqtt.yaml
sems2mqtt: !include sems2mqtt.yaml

binary_sensor opnsense: !include includes/sensors/rest_binary_sensor_opnsense.yaml
rest: !include_dir_merge_list includes/sensors/rest/
rest_command: !include includes/rest_commands/rest_commands.yaml
script opnsense: !include includes/scripts/script_opnsense.yaml
script arrs: !include includes/scripts/script_arrs.yaml
input_select: !include includes/helpers/input_select.yaml
input_boolean: !include includes/helpers/input_boolean.yaml
automation opnsense: !include includes/automations/automation_opnsense.yaml
automation dispatcharr: !include includes/automations/automation_dispatcharr.yaml
switch opnsense: !include includes/switches/switch_opnsense.yaml
shell_command: !include includes/shell_commands/shell_commands.yaml

lovelace:
  mode: storage
  dashboards:
    dashboard-opnsense:
      mode: yaml
      title: OPNSense
      show_in_sidebar: true
      filename: includes/dashboards/dashboard_opnsense.yaml
    dashboard-teslamate:
      mode: yaml
      title: Teslamate
      show_in_sidebar: true
      filename: includes/dashboards/dashboard_teslamate.yaml
    dashboard-plex:
      mode: yaml
      title: Plex
      show_in_sidebar: true
      filename: includes/dashboards/dashboard_plex.yaml