- platform: rest
  unique_id: airvpn_server
  name: AirVPN server
  resource: https://opnsense.mcfly.net/api/wireguard/server/getServer/b007cda3-7d52-472e-96b9-f0b4a8bf4ff8
  method: GET
  verify_ssl: false
  authentication: basic
  username: !secret opns_key
  password: !secret opns_secret
  value_template: >
    {% set data = namespace(servers = []) %}
    {% set peers = merge_response(value_json.server.peers) %}
    {% for peer in peers %}
      {% if peer.selected %}
        {% set data.servers = data.servers + [peer.value] %}
      {% endif %}
    {% endfor %}
    {% if data.servers %}
      {{ data.servers | join(' ') }}
    {% else %}
      Not connected
    {% endif %}